apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mycontainer
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts: # pod path
        - name: myefsvolume # use 
          mountPath: /usr/share/nginx/html
      volumes: # worker node path
      - name: myefsvolume # create 
        nfs:     
          path: /data
          server: fs-06c0771651da08cab.efs.eu-north-1.amazonaws.com